---
docname: "Curriculum Vitae"
name: Hongsun
surname: Kim
position: "Clinical Fellow"
#pronouns: he/his/him
address: "Department of Cardiovascular Surgery, Mayo Clinic, Rochester, MN"
profilepic: "../Input/Hongsun Kim.jpg"
phone: +1 213 563 1989
linkedin: "hongsun-kim"
email: "kim.hongsun@mayo.edu, yoursunny@gmail.com"
researchgate: "Hongsun-Kim-2"
orcid: 0000-0002-1879-4553
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Cardiac Surgeon & Researcher \\newline  Interest in Aortic surgery & Thoracic transplantation"


output: 
  vitae::moderncv:
    pandoc_args: ["--lua-filter=../lua/bold.lua"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readr)
```

# Education

```{r}
library(tibble)
read_csv("../Input/education.csv") %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Work Experience

```{r}
read_csv("../Input/experience.csv") %>% 
  detailed_entries(Position, Year, Institution, Where)
```

# Presentations
```{r}
read_csv("../Input/presentation.csv") %>% 
  brief_entries(
    Title,
    Year,
    Conference
  )
```

# Publications

```{r}
library(dplyr)
#knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("../Input/my_publications.bib") %>%
  arrange(desc(issued),desc(author$family))
```

