---
docname: "Curriculum Vitae"
name: Hongsun
surname: Kim
position: "Clinical Fellow"
#pronouns: he/his/him
address: "Department of Cardiovascular Surgery, Mayo Clinic, Rochester, MN"
profilepic: "../Input/Hongsun Kim.jpg"
phone: +1 213 563 1989
linkedin: "hongsun-kim"
email: "kim.hongsun@mayo.edu, yoursunny@gmail.com"
researchgate: "Hongsun-Kim-2"
orcid: 0000-0002-1879-4553
headcolor: 009ACD
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Cardiac Surgeon & Researcher \\newline Interest in Aortic surgery & Thoracic transplantation"
latex_engine: xelatex
csl: "../apa-cv.csl"
#biblography: "../Input/my_publications_test.bib"
output:
  vitae::awesomecv:
    keep_tex: true
    pandoc_args: ["--lua-filter=../lua/strong.lua"]
    includes:
      in_header: header.txt
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(readr)
library(fontawesome)
```



\faIcon{university} Education
============================

```{r}
library(tibble)
read_csv("../Input/education.csv") %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

\faIcon{briefcase} Work Experience
============================

```{r}
read_csv("../Input/experience.csv") %>% 
  detailed_entries(Position, Year, Institution,Where)
```

\faIcon{comments} Presentations
============================

```{r, results='asis'}
read_csv("../Input/presentation.csv") %>% 
  detailed_entries(what=Conference,when=Year,with=Title)
```

\faIcon*{file} Publications
============================

```{r results='asis'}
library(dplyr)

bibliography_entries("../Input/my_publications.bib") %>%
  arrange(desc(issued),desc(author$family))

```
