---
name: Lorena Abad
position: "Researching the Environment through Geospatial Technologies"
address: |
         | Schillerstraße 30, 5020 Salzburg, Austria
phone: +43 662 8044 7582 
email: "lorena.abad@plus.ac.at"
twitter: loreabad6
mastodon: loreabad6@fosstodon.org
github: loreabad6
linkedin: lorena-abad
researchgate: Lorena_Abad2
orcid: 0000-0003-0554-734X
headcolor: 009ACD
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    keep_tex: false
    show_footer: true
    includes:
      in_header: header.txt
always_allow_html: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(ggplot2)
library(dplyr)
library(sf)
library(rnaturalearth)
library(sfnetworks)
library(ggrepel)
library(emojifont)
library(fontawesome)
library(kableExtra)
library(huxtable)
library(gridExtra)
```

```{r}
# \paragraphstyle{I am an environmental engineer from Cuenca, Ecuador specialized in Geospatial Technologies, expected by March 2019. My research scope includes spatial data analysis, particularly focused on R programming; remote sensing and earth observation data analysis, specially optical satellite imagery applied to environmental studies and analyses such as air pollution, land use/land cover change; geostatistical analysis of climate data; and ecological modelling. I feel very keen to pursue a career in research, science, and academia.}
```

<!-- | Nationality: Ecuadorian, Birthdate: 05/01/1994 -->

\faIcon{plane} My journey
============================

\faIcon{briefcase} Professional Experience
============================================

\faIcon*{file} Selected Publications
===========================

\scriptsize
